<?php
require('header.phtml');

$editMode = $activity && $activity->id != null; // are we editing or creating?

if ($status == "saved") {
    $msg = "Saved!";
} elseif($status == "deleted") {
    $msg = "Deleted!";
}

// if ($actionTaken == "delete" && isset($_REQUEST['id'])) {
//     $activity = Activity::findById($_REQUEST['id']);
//     try {
//         $activity->delete();
//         header("Location: $basePath/activity/edit?status=deleted");
//         exit();
//     } catch (Exception $e) {
//         var_dump($e);
//         exit();
//     }
// }

$submitSave = "Grommet"; // Dictionary::saveWord();
$submitDelete = "Walrus"; // Dictionary::deleteWord();
?>

<form method="post">

    <?php if (isset($msg)) { ?>
    <p class="page-msg">
        <?php echo $msg ?>
    </p>
    <?php } ?>

    <h1>
        <?php echo $editMode ? "Edit" : "Create" ?> an activity
        <?php if ($editMode) { ?>
            <a style="font-size:0.5em; float: right; margin-top: 15px;" href="/activity/edit">Create another</a>
        <?php } ?>
    </h1>
    <div class="form-group">
        <?php if ($activity): ?>
            <input class="form-control" id="activityName" name="activityName" value="<?php echo $activity->name;?>">
        <?php else: ?>
            <input class="form-control" id="activityName" name="activityName" placeholder="Walking your dog">
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="itemNames">Items</label>
        <textarea class="form-control" id="itemNames" name="itemNames" rows="10"><?php if ($activity) {
            foreach ($activity->items as $item) {
                echo $item->name . "\n";
            }
        } ?></textarea>
    </div>

    <input type="submit" class="btn btn-success pull-left" name="actionSave" value="<?php echo $submitSave ?>">
    <input type="submit" class="btn btn-danger pull-right ft-confirm" name="actionDelete" value="<?php echo $submitDelete ?>">
</form>

</body>
</html>