<?php
$replCount = 3;
require('header.phtml');
?>

<p>You are <span class='activity'><?php echo $activity->name; ?></span>.</p>

<?php
foreach ($activity->randomActivityItems($replCount) as $item) {
    $replItem = $replacements[--$replCount];

    echo "<p><span class='attr'>" . ucfirst($item->name) . "</span> " . \FiveThings\Utils::isAre($item->name) . " <span class='repl'>" . $replItem->article . " " . $replItem->name . ".</span></p>";
}
?>

</body>
</html>