<?php
  $basePath = ""; // TODO
?><!doctype html>
<html>
<head>
    <title>5 Things Generator</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<?php echo $basePath?>/static/css/fivethings.css">
    <script src="<?php echo $basePath?>/static/js/fivethings.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-712631-7"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-712631-7');
    </script>

</head>
<body>

<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand" href="#">5 Things Generator</span>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="<?php echo $basePath ?>/">Get Suggestions</a></li>
      <li><a href="<?php echo $basePath ?>/simple">Simple Mode</a></li>
      <li><a href="<?php echo $basePath ?>/activity/list">Database</a></li>
      <li><a href="https://github.com/dkurth/5things">GitHub</a></li>
    </ul>
  </div>
</nav>
